<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>localhost</groupId>
  <artifactId>protobuf-javanano-latest</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <name>libyear-report</name>

  <description>Test to verify that protobuf-javanano:3.2.0rc2 is the latest version</description>
  <url>http://localhost/</url>

  <dependencies>
    <dependency>
      <groupId>com.google.protobuf.nano</groupId>
      <artifactId>protobuf-javanano</artifactId>
      <version>3.2.0rc2</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.github.mfoo</groupId>
        <artifactId>libyear-maven-plugin</artifactId>
        <version>${project.version}</version>
        <configuration>
          <reportFile>protobuf-report.csv</reportFile>
          <minLibYearsForReport>0.0</minLibYearsForReport>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>analyze</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
